[package]
name = "perf-and-dhat-profiling-example"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.6"
dhat = "0.2.2"

[profile.release]
incremental = true
debug = true
#lto = "fat"
#codegen-units = 1

[features]
default = []
dhat-on = []


