[package]
name = "perf-and-dhat-profiling-example"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.6"
serde_bytes = "0.11.5"
dhat = "0.2.2"

[profile.release]
incremental = true
debug = true
#lto = "fat"

[features]
default = []
dhat-on = []
